#pragma once

#include <stdint.h>

#define RCC_BOUNDARY_ADDRESS 0x40023800
#define RCC_AHB1ENR (RCC_BOUNDARY_ADDRESS + 0x30)
#define GPIOAEN 0

#define GPIO_MODER_OFFSET 0x0
#define GPIO_OTYPER_OFFSET 0x4
#define GPIO_PUPDR_OFFSET 0xC
#define GPIO_ODR_OFFSET 0x14

#define GPIOA_BOUNDARY_ADDRESS 0x40020000
#define GPIOA_MODER (GPIOA_BOUNDARY_ADDRESS + GPIO_MODER_OFFSET)
#define GPIOA_OTYPER (GPIOA_BOUNDARY_ADDRESS + GPIO_OTYPER_OFFSET)
#define GPIOA_PUPDR (GPIOA_BOUNDARY_ADDRESS + GPIO_PUPDR_OFFSET)
#define GPIOA_ODR (GPIOA_BOUNDARY_ADDRESS + GPIO_ODR_OFFSET)

#define PA8 8

void led_enable(void);
void led_on(void);
void led_off(void);
